language: python
python:
    - '3.6'
install:
    - pip install -r requirements.txt
    - python install .
script:
    - tools/check_code.sh
    - pytest -v --cov-report term-missing --cov=pyroc tests
