language: python
python:
    - '3.6'
    - '3.7'
install:
    - pip install -r requirements.txt
script:
    - tools/check_code.sh
    - pytest -v tests
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
